//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NORTHWNDEntities : DbContext
    {
        public NORTHWNDEntities()
            : base("name=NORTHWNDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CustomerDemographics> CustomerDemographics { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Shippers> Shippers { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Territories> Territories { get; set; }
        public virtual DbSet<vm_productos_north> vm_productos_north { get; set; }
    
        public virtual int SP_CapacitacionAp2(string pcNombre, string pcApellido, string pcTelefono, Nullable<int> pnCodigo, ObjectParameter pcResult, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcMensajeError)
        {
            var pcNombreParameter = pcNombre != null ?
                new ObjectParameter("pcNombre", pcNombre) :
                new ObjectParameter("pcNombre", typeof(string));
    
            var pcApellidoParameter = pcApellido != null ?
                new ObjectParameter("pcApellido", pcApellido) :
                new ObjectParameter("pcApellido", typeof(string));
    
            var pcTelefonoParameter = pcTelefono != null ?
                new ObjectParameter("pcTelefono", pcTelefono) :
                new ObjectParameter("pcTelefono", typeof(string));
    
            var pnCodigoParameter = pnCodigo.HasValue ?
                new ObjectParameter("pnCodigo", pnCodigo) :
                new ObjectParameter("pnCodigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CapacitacionAp2", pcNombreParameter, pcApellidoParameter, pcTelefonoParameter, pnCodigoParameter, pcResult, pnTypeResult, pnCodeResult, pcMensajeError);
        }
    
        public virtual int SP_CapacitacionApi(string pcNombre, ObjectParameter pcResult, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcMessage)
        {
            var pcNombreParameter = pcNombre != null ?
                new ObjectParameter("pcNombre", pcNombre) :
                new ObjectParameter("pcNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CapacitacionApi", pcNombreParameter, pcResult, pnTypeResult, pnCodeResult, pcMessage);
        }
    
        public virtual int SP_Gestion_Clientes(Nullable<int> pnTipoOperacion, string pcIdCliente, string pcNombreCompania, string pcNombreContacto, string pcTituloContacto, string pcDireccion, string pcCiudad, string pcRegion, string pcCodigoPostal, string pcPais, string pcTelefono, string pcFax, ObjectParameter pcResult, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pcIdClienteParameter = pcIdCliente != null ?
                new ObjectParameter("pcIdCliente", pcIdCliente) :
                new ObjectParameter("pcIdCliente", typeof(string));
    
            var pcNombreCompaniaParameter = pcNombreCompania != null ?
                new ObjectParameter("pcNombreCompania", pcNombreCompania) :
                new ObjectParameter("pcNombreCompania", typeof(string));
    
            var pcNombreContactoParameter = pcNombreContacto != null ?
                new ObjectParameter("pcNombreContacto", pcNombreContacto) :
                new ObjectParameter("pcNombreContacto", typeof(string));
    
            var pcTituloContactoParameter = pcTituloContacto != null ?
                new ObjectParameter("pcTituloContacto", pcTituloContacto) :
                new ObjectParameter("pcTituloContacto", typeof(string));
    
            var pcDireccionParameter = pcDireccion != null ?
                new ObjectParameter("pcDireccion", pcDireccion) :
                new ObjectParameter("pcDireccion", typeof(string));
    
            var pcCiudadParameter = pcCiudad != null ?
                new ObjectParameter("pcCiudad", pcCiudad) :
                new ObjectParameter("pcCiudad", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcCodigoPostalParameter = pcCodigoPostal != null ?
                new ObjectParameter("pcCodigoPostal", pcCodigoPostal) :
                new ObjectParameter("pcCodigoPostal", typeof(string));
    
            var pcPaisParameter = pcPais != null ?
                new ObjectParameter("pcPais", pcPais) :
                new ObjectParameter("pcPais", typeof(string));
    
            var pcTelefonoParameter = pcTelefono != null ?
                new ObjectParameter("pcTelefono", pcTelefono) :
                new ObjectParameter("pcTelefono", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Gestion_Clientes", pnTipoOperacionParameter, pcIdClienteParameter, pcNombreCompaniaParameter, pcNombreContactoParameter, pcTituloContactoParameter, pcDireccionParameter, pcCiudadParameter, pcRegionParameter, pcCodigoPostalParameter, pcPaisParameter, pcTelefonoParameter, pcFaxParameter, pcResult, pnTypeResult, pnCodeResult, pcMessage);
        }
    
        public virtual int SP_Manage_Supplier(Nullable<int> pnOperationType, Nullable<int> pnSupplierID, string pcCompanyName, string pcContactName, string pcContactTitle, string pcAddress, string pcCity, string pcRegion, string pcPostalCode, string pcCountry, string pcPhone, string pcFax, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnOperationTypeParameter = pnOperationType.HasValue ?
                new ObjectParameter("pnOperationType", pnOperationType) :
                new ObjectParameter("pnOperationType", typeof(int));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pcCompanyNameParameter = pcCompanyName != null ?
                new ObjectParameter("pcCompanyName", pcCompanyName) :
                new ObjectParameter("pcCompanyName", typeof(string));
    
            var pcContactNameParameter = pcContactName != null ?
                new ObjectParameter("pcContactName", pcContactName) :
                new ObjectParameter("pcContactName", typeof(string));
    
            var pcContactTitleParameter = pcContactTitle != null ?
                new ObjectParameter("pcContactTitle", pcContactTitle) :
                new ObjectParameter("pcContactTitle", typeof(string));
    
            var pcAddressParameter = pcAddress != null ?
                new ObjectParameter("pcAddress", pcAddress) :
                new ObjectParameter("pcAddress", typeof(string));
    
            var pcCityParameter = pcCity != null ?
                new ObjectParameter("pcCity", pcCity) :
                new ObjectParameter("pcCity", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcPostalCodeParameter = pcPostalCode != null ?
                new ObjectParameter("pcPostalCode", pcPostalCode) :
                new ObjectParameter("pcPostalCode", typeof(string));
    
            var pcCountryParameter = pcCountry != null ?
                new ObjectParameter("pcCountry", pcCountry) :
                new ObjectParameter("pcCountry", typeof(string));
    
            var pcPhoneParameter = pcPhone != null ?
                new ObjectParameter("pcPhone", pcPhone) :
                new ObjectParameter("pcPhone", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Manage_Supplier", pnOperationTypeParameter, pnSupplierIDParameter, pcCompanyNameParameter, pcContactNameParameter, pcContactTitleParameter, pcAddressParameter, pcCityParameter, pcRegionParameter, pcPostalCodeParameter, pcCountryParameter, pcPhoneParameter, pcFaxParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_slagos_gestionar_categorias(Nullable<int> pnTipoOperacion, Nullable<int> pnCategoryID, string pcCategoryName, string pcDescription, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcCategoryNameParameter = pcCategoryName != null ?
                new ObjectParameter("pcCategoryName", pcCategoryName) :
                new ObjectParameter("pcCategoryName", typeof(string));
    
            var pcDescriptionParameter = pcDescription != null ?
                new ObjectParameter("pcDescription", pcDescription) :
                new ObjectParameter("pcDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_slagos_gestionar_categorias", pnTipoOperacionParameter, pnCategoryIDParameter, pcCategoryNameParameter, pcDescriptionParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_slagos_gestionar_productos(Nullable<int> pnTipoOperacion, Nullable<int> pnProductID, string pcProductName, Nullable<int> pnSupplierID, Nullable<int> pnCategoryID, string pcQuantityPerUnit, Nullable<decimal> pnUnitPrice, Nullable<short> pnUnitsInStock, Nullable<short> pnUnitsOnOrder, Nullable<short> pnReorderLevel, Nullable<bool> pnDiscontinued, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnProductIDParameter = pnProductID.HasValue ?
                new ObjectParameter("pnProductID", pnProductID) :
                new ObjectParameter("pnProductID", typeof(int));
    
            var pcProductNameParameter = pcProductName != null ?
                new ObjectParameter("pcProductName", pcProductName) :
                new ObjectParameter("pcProductName", typeof(string));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcQuantityPerUnitParameter = pcQuantityPerUnit != null ?
                new ObjectParameter("pcQuantityPerUnit", pcQuantityPerUnit) :
                new ObjectParameter("pcQuantityPerUnit", typeof(string));
    
            var pnUnitPriceParameter = pnUnitPrice.HasValue ?
                new ObjectParameter("pnUnitPrice", pnUnitPrice) :
                new ObjectParameter("pnUnitPrice", typeof(decimal));
    
            var pnUnitsInStockParameter = pnUnitsInStock.HasValue ?
                new ObjectParameter("pnUnitsInStock", pnUnitsInStock) :
                new ObjectParameter("pnUnitsInStock", typeof(short));
    
            var pnUnitsOnOrderParameter = pnUnitsOnOrder.HasValue ?
                new ObjectParameter("pnUnitsOnOrder", pnUnitsOnOrder) :
                new ObjectParameter("pnUnitsOnOrder", typeof(short));
    
            var pnReorderLevelParameter = pnReorderLevel.HasValue ?
                new ObjectParameter("pnReorderLevel", pnReorderLevel) :
                new ObjectParameter("pnReorderLevel", typeof(short));
    
            var pnDiscontinuedParameter = pnDiscontinued.HasValue ?
                new ObjectParameter("pnDiscontinued", pnDiscontinued) :
                new ObjectParameter("pnDiscontinued", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_slagos_gestionar_productos", pnTipoOperacionParameter, pnProductIDParameter, pcProductNameParameter, pnSupplierIDParameter, pnCategoryIDParameter, pcQuantityPerUnitParameter, pnUnitPriceParameter, pnUnitsInStockParameter, pnUnitsOnOrderParameter, pnReorderLevelParameter, pnDiscontinuedParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_slagos_gestionar_proveedores(Nullable<int> pnTipoOperacion, Nullable<int> pnSupplierID, string pcCompanyName, string pcContactName, string pcContactTitle, string pcCity, string pcRegion, string pcPostalCode, string pcCountry, string pcPhone, string pcHomePage, string pcAddress, string pcFax, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pcCompanyNameParameter = pcCompanyName != null ?
                new ObjectParameter("pcCompanyName", pcCompanyName) :
                new ObjectParameter("pcCompanyName", typeof(string));
    
            var pcContactNameParameter = pcContactName != null ?
                new ObjectParameter("pcContactName", pcContactName) :
                new ObjectParameter("pcContactName", typeof(string));
    
            var pcContactTitleParameter = pcContactTitle != null ?
                new ObjectParameter("pcContactTitle", pcContactTitle) :
                new ObjectParameter("pcContactTitle", typeof(string));
    
            var pcCityParameter = pcCity != null ?
                new ObjectParameter("pcCity", pcCity) :
                new ObjectParameter("pcCity", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcPostalCodeParameter = pcPostalCode != null ?
                new ObjectParameter("pcPostalCode", pcPostalCode) :
                new ObjectParameter("pcPostalCode", typeof(string));
    
            var pcCountryParameter = pcCountry != null ?
                new ObjectParameter("pcCountry", pcCountry) :
                new ObjectParameter("pcCountry", typeof(string));
    
            var pcPhoneParameter = pcPhone != null ?
                new ObjectParameter("pcPhone", pcPhone) :
                new ObjectParameter("pcPhone", typeof(string));
    
            var pcHomePageParameter = pcHomePage != null ?
                new ObjectParameter("pcHomePage", pcHomePage) :
                new ObjectParameter("pcHomePage", typeof(string));
    
            var pcAddressParameter = pcAddress != null ?
                new ObjectParameter("pcAddress", pcAddress) :
                new ObjectParameter("pcAddress", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_slagos_gestionar_proveedores", pnTipoOperacionParameter, pnSupplierIDParameter, pcCompanyNameParameter, pcContactNameParameter, pcContactTitleParameter, pcCityParameter, pcRegionParameter, pcPostalCodeParameter, pcCountryParameter, pcPhoneParameter, pcHomePageParameter, pcAddressParameter, pcFaxParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_bvelasquez_gestion_catego(Nullable<int> pnTipoOperacion, Nullable<int> pnCodigoRegistro, Nullable<int> pnCategoryID, string pcCategoryName, string pcDescription, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCodigoRegistroParameter = pnCodigoRegistro.HasValue ?
                new ObjectParameter("pnCodigoRegistro", pnCodigoRegistro) :
                new ObjectParameter("pnCodigoRegistro", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcCategoryNameParameter = pcCategoryName != null ?
                new ObjectParameter("pcCategoryName", pcCategoryName) :
                new ObjectParameter("pcCategoryName", typeof(string));
    
            var pcDescriptionParameter = pcDescription != null ?
                new ObjectParameter("pcDescription", pcDescription) :
                new ObjectParameter("pcDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_bvelasquez_gestion_catego", pnTipoOperacionParameter, pnCodigoRegistroParameter, pnCategoryIDParameter, pcCategoryNameParameter, pcDescriptionParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_bvelasquez_gestion_prod(Nullable<int> pnTipoOperacion, Nullable<int> pnCodigoRegistro, Nullable<int> pnProductID, string pcProductName, Nullable<int> pnSupplierID, Nullable<int> pnCategoryID, string pcQuantityPerUnit, Nullable<decimal> pnUnitPrice, Nullable<short> pnUnitsInStock, Nullable<short> pnUnitsOnOrder, Nullable<short> pnReorderLevel, Nullable<bool> pnDiscontinued, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCodigoRegistroParameter = pnCodigoRegistro.HasValue ?
                new ObjectParameter("pnCodigoRegistro", pnCodigoRegistro) :
                new ObjectParameter("pnCodigoRegistro", typeof(int));
    
            var pnProductIDParameter = pnProductID.HasValue ?
                new ObjectParameter("pnProductID", pnProductID) :
                new ObjectParameter("pnProductID", typeof(int));
    
            var pcProductNameParameter = pcProductName != null ?
                new ObjectParameter("pcProductName", pcProductName) :
                new ObjectParameter("pcProductName", typeof(string));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcQuantityPerUnitParameter = pcQuantityPerUnit != null ?
                new ObjectParameter("pcQuantityPerUnit", pcQuantityPerUnit) :
                new ObjectParameter("pcQuantityPerUnit", typeof(string));
    
            var pnUnitPriceParameter = pnUnitPrice.HasValue ?
                new ObjectParameter("pnUnitPrice", pnUnitPrice) :
                new ObjectParameter("pnUnitPrice", typeof(decimal));
    
            var pnUnitsInStockParameter = pnUnitsInStock.HasValue ?
                new ObjectParameter("pnUnitsInStock", pnUnitsInStock) :
                new ObjectParameter("pnUnitsInStock", typeof(short));
    
            var pnUnitsOnOrderParameter = pnUnitsOnOrder.HasValue ?
                new ObjectParameter("pnUnitsOnOrder", pnUnitsOnOrder) :
                new ObjectParameter("pnUnitsOnOrder", typeof(short));
    
            var pnReorderLevelParameter = pnReorderLevel.HasValue ?
                new ObjectParameter("pnReorderLevel", pnReorderLevel) :
                new ObjectParameter("pnReorderLevel", typeof(short));
    
            var pnDiscontinuedParameter = pnDiscontinued.HasValue ?
                new ObjectParameter("pnDiscontinued", pnDiscontinued) :
                new ObjectParameter("pnDiscontinued", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_bvelasquez_gestion_prod", pnTipoOperacionParameter, pnCodigoRegistroParameter, pnProductIDParameter, pcProductNameParameter, pnSupplierIDParameter, pnCategoryIDParameter, pcQuantityPerUnitParameter, pnUnitPriceParameter, pnUnitsInStockParameter, pnUnitsOnOrderParameter, pnReorderLevelParameter, pnDiscontinuedParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_bvelasquez_gestion_suppliers(Nullable<int> pnTipoOperacion, Nullable<int> pnSupplierID, string pcCompanyName, string pcContactName, string pcContactTitle, string pcCity, string pcRegion, string pcPostalCode, string pcCountry, string pcPhone, string pcHomePage, string pcAddress, string pcFax, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pcCompanyNameParameter = pcCompanyName != null ?
                new ObjectParameter("pcCompanyName", pcCompanyName) :
                new ObjectParameter("pcCompanyName", typeof(string));
    
            var pcContactNameParameter = pcContactName != null ?
                new ObjectParameter("pcContactName", pcContactName) :
                new ObjectParameter("pcContactName", typeof(string));
    
            var pcContactTitleParameter = pcContactTitle != null ?
                new ObjectParameter("pcContactTitle", pcContactTitle) :
                new ObjectParameter("pcContactTitle", typeof(string));
    
            var pcCityParameter = pcCity != null ?
                new ObjectParameter("pcCity", pcCity) :
                new ObjectParameter("pcCity", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcPostalCodeParameter = pcPostalCode != null ?
                new ObjectParameter("pcPostalCode", pcPostalCode) :
                new ObjectParameter("pcPostalCode", typeof(string));
    
            var pcCountryParameter = pcCountry != null ?
                new ObjectParameter("pcCountry", pcCountry) :
                new ObjectParameter("pcCountry", typeof(string));
    
            var pcPhoneParameter = pcPhone != null ?
                new ObjectParameter("pcPhone", pcPhone) :
                new ObjectParameter("pcPhone", typeof(string));
    
            var pcHomePageParameter = pcHomePage != null ?
                new ObjectParameter("pcHomePage", pcHomePage) :
                new ObjectParameter("pcHomePage", typeof(string));
    
            var pcAddressParameter = pcAddress != null ?
                new ObjectParameter("pcAddress", pcAddress) :
                new ObjectParameter("pcAddress", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_bvelasquez_gestion_suppliers", pnTipoOperacionParameter, pnSupplierIDParameter, pcCompanyNameParameter, pcContactNameParameter, pcContactTitleParameter, pcCityParameter, pcRegionParameter, pcPostalCodeParameter, pcCountryParameter, pcPhoneParameter, pcHomePageParameter, pcAddressParameter, pcFaxParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_gamador_gestion_categories(Nullable<int> pnTipoOperacion, Nullable<int> pnCodigoRegistro, string pcCategoryName, string pcDescription, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCodigoRegistroParameter = pnCodigoRegistro.HasValue ?
                new ObjectParameter("pnCodigoRegistro", pnCodigoRegistro) :
                new ObjectParameter("pnCodigoRegistro", typeof(int));
    
            var pcCategoryNameParameter = pcCategoryName != null ?
                new ObjectParameter("pcCategoryName", pcCategoryName) :
                new ObjectParameter("pcCategoryName", typeof(string));
    
            var pcDescriptionParameter = pcDescription != null ?
                new ObjectParameter("pcDescription", pcDescription) :
                new ObjectParameter("pcDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_gamador_gestion_categories", pnTipoOperacionParameter, pnCodigoRegistroParameter, pcCategoryNameParameter, pcDescriptionParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_gamador_gestion_products(Nullable<int> pnTipoOperacion, Nullable<int> pnCodigoRegistro, string pcProductName, Nullable<int> pnSupplier, Nullable<int> pnCategoryID, string pcnQuantityPerUnit, Nullable<decimal> pnUnitPrice, Nullable<int> pnUnitsInStock, Nullable<int> pnUnitsOnOrder, Nullable<int> pnReorderLevel, Nullable<bool> pbDiscontinued, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCodigoRegistroParameter = pnCodigoRegistro.HasValue ?
                new ObjectParameter("pnCodigoRegistro", pnCodigoRegistro) :
                new ObjectParameter("pnCodigoRegistro", typeof(int));
    
            var pcProductNameParameter = pcProductName != null ?
                new ObjectParameter("pcProductName", pcProductName) :
                new ObjectParameter("pcProductName", typeof(string));
    
            var pnSupplierParameter = pnSupplier.HasValue ?
                new ObjectParameter("pnSupplier", pnSupplier) :
                new ObjectParameter("pnSupplier", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcnQuantityPerUnitParameter = pcnQuantityPerUnit != null ?
                new ObjectParameter("pcnQuantityPerUnit", pcnQuantityPerUnit) :
                new ObjectParameter("pcnQuantityPerUnit", typeof(string));
    
            var pnUnitPriceParameter = pnUnitPrice.HasValue ?
                new ObjectParameter("pnUnitPrice", pnUnitPrice) :
                new ObjectParameter("pnUnitPrice", typeof(decimal));
    
            var pnUnitsInStockParameter = pnUnitsInStock.HasValue ?
                new ObjectParameter("pnUnitsInStock", pnUnitsInStock) :
                new ObjectParameter("pnUnitsInStock", typeof(int));
    
            var pnUnitsOnOrderParameter = pnUnitsOnOrder.HasValue ?
                new ObjectParameter("pnUnitsOnOrder", pnUnitsOnOrder) :
                new ObjectParameter("pnUnitsOnOrder", typeof(int));
    
            var pnReorderLevelParameter = pnReorderLevel.HasValue ?
                new ObjectParameter("pnReorderLevel", pnReorderLevel) :
                new ObjectParameter("pnReorderLevel", typeof(int));
    
            var pbDiscontinuedParameter = pbDiscontinued.HasValue ?
                new ObjectParameter("pbDiscontinued", pbDiscontinued) :
                new ObjectParameter("pbDiscontinued", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_gamador_gestion_products", pnTipoOperacionParameter, pnCodigoRegistroParameter, pcProductNameParameter, pnSupplierParameter, pnCategoryIDParameter, pcnQuantityPerUnitParameter, pnUnitPriceParameter, pnUnitsInStockParameter, pnUnitsOnOrderParameter, pnReorderLevelParameter, pbDiscontinuedParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_gamador_gestion_suppliers(Nullable<int> pnTipoOperacion, Nullable<int> pnCodigoRegistro, string pcCompanyName, string pcContactName, string pcContactTitle, string pcCity, string pcRegion, string pcPostalCode, string pcCountry, string pcPhone, string pcHomePage, string pcAddress, string pcFax, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCodigoRegistroParameter = pnCodigoRegistro.HasValue ?
                new ObjectParameter("pnCodigoRegistro", pnCodigoRegistro) :
                new ObjectParameter("pnCodigoRegistro", typeof(int));
    
            var pcCompanyNameParameter = pcCompanyName != null ?
                new ObjectParameter("pcCompanyName", pcCompanyName) :
                new ObjectParameter("pcCompanyName", typeof(string));
    
            var pcContactNameParameter = pcContactName != null ?
                new ObjectParameter("pcContactName", pcContactName) :
                new ObjectParameter("pcContactName", typeof(string));
    
            var pcContactTitleParameter = pcContactTitle != null ?
                new ObjectParameter("pcContactTitle", pcContactTitle) :
                new ObjectParameter("pcContactTitle", typeof(string));
    
            var pcCityParameter = pcCity != null ?
                new ObjectParameter("pcCity", pcCity) :
                new ObjectParameter("pcCity", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcPostalCodeParameter = pcPostalCode != null ?
                new ObjectParameter("pcPostalCode", pcPostalCode) :
                new ObjectParameter("pcPostalCode", typeof(string));
    
            var pcCountryParameter = pcCountry != null ?
                new ObjectParameter("pcCountry", pcCountry) :
                new ObjectParameter("pcCountry", typeof(string));
    
            var pcPhoneParameter = pcPhone != null ?
                new ObjectParameter("pcPhone", pcPhone) :
                new ObjectParameter("pcPhone", typeof(string));
    
            var pcHomePageParameter = pcHomePage != null ?
                new ObjectParameter("pcHomePage", pcHomePage) :
                new ObjectParameter("pcHomePage", typeof(string));
    
            var pcAddressParameter = pcAddress != null ?
                new ObjectParameter("pcAddress", pcAddress) :
                new ObjectParameter("pcAddress", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_gamador_gestion_suppliers", pnTipoOperacionParameter, pnCodigoRegistroParameter, pcCompanyNameParameter, pcContactNameParameter, pcContactTitleParameter, pcCityParameter, pcRegionParameter, pcPostalCodeParameter, pcCountryParameter, pcPhoneParameter, pcHomePageParameter, pcAddressParameter, pcFaxParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_gmaradiaga_gestion_categorias(Nullable<int> pnTipoOperacion, Nullable<int> pnCategoryID, string pcCategoryName, string pcDescription, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcCategoryNameParameter = pcCategoryName != null ?
                new ObjectParameter("pcCategoryName", pcCategoryName) :
                new ObjectParameter("pcCategoryName", typeof(string));
    
            var pcDescriptionParameter = pcDescription != null ?
                new ObjectParameter("pcDescription", pcDescription) :
                new ObjectParameter("pcDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_gmaradiaga_gestion_categorias", pnTipoOperacionParameter, pnCategoryIDParameter, pcCategoryNameParameter, pcDescriptionParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_gmaradiaga_gestion_products(Nullable<int> pnTipoOperacion, Nullable<int> pnProductID, string pcProductName, Nullable<int> pnSupplierID, Nullable<int> pnCategoryID, string pcQuantityPerUnit, Nullable<decimal> pnUnitPrice, Nullable<short> pnUnitsInStock, Nullable<short> pnUnitsOnOrder, Nullable<short> pnReorderLevel, Nullable<bool> pnDiscontinued, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnProductIDParameter = pnProductID.HasValue ?
                new ObjectParameter("pnProductID", pnProductID) :
                new ObjectParameter("pnProductID", typeof(int));
    
            var pcProductNameParameter = pcProductName != null ?
                new ObjectParameter("pcProductName", pcProductName) :
                new ObjectParameter("pcProductName", typeof(string));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcQuantityPerUnitParameter = pcQuantityPerUnit != null ?
                new ObjectParameter("pcQuantityPerUnit", pcQuantityPerUnit) :
                new ObjectParameter("pcQuantityPerUnit", typeof(string));
    
            var pnUnitPriceParameter = pnUnitPrice.HasValue ?
                new ObjectParameter("pnUnitPrice", pnUnitPrice) :
                new ObjectParameter("pnUnitPrice", typeof(decimal));
    
            var pnUnitsInStockParameter = pnUnitsInStock.HasValue ?
                new ObjectParameter("pnUnitsInStock", pnUnitsInStock) :
                new ObjectParameter("pnUnitsInStock", typeof(short));
    
            var pnUnitsOnOrderParameter = pnUnitsOnOrder.HasValue ?
                new ObjectParameter("pnUnitsOnOrder", pnUnitsOnOrder) :
                new ObjectParameter("pnUnitsOnOrder", typeof(short));
    
            var pnReorderLevelParameter = pnReorderLevel.HasValue ?
                new ObjectParameter("pnReorderLevel", pnReorderLevel) :
                new ObjectParameter("pnReorderLevel", typeof(short));
    
            var pnDiscontinuedParameter = pnDiscontinued.HasValue ?
                new ObjectParameter("pnDiscontinued", pnDiscontinued) :
                new ObjectParameter("pnDiscontinued", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_gmaradiaga_gestion_products", pnTipoOperacionParameter, pnProductIDParameter, pcProductNameParameter, pnSupplierIDParameter, pnCategoryIDParameter, pcQuantityPerUnitParameter, pnUnitPriceParameter, pnUnitsInStockParameter, pnUnitsOnOrderParameter, pnReorderLevelParameter, pnDiscontinuedParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_gmaradiaga_gestion_suppliers(Nullable<int> pnTipoOperacion, Nullable<int> pnSupplierID, string pcCompanyName, string pcContactName, string pcContactTitle, string pcCity, string pcRegion, string pcPostalCode, string pcCountry, string pcPhone, string pcHomePage, string pcAddress, string pcFax, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pcCompanyNameParameter = pcCompanyName != null ?
                new ObjectParameter("pcCompanyName", pcCompanyName) :
                new ObjectParameter("pcCompanyName", typeof(string));
    
            var pcContactNameParameter = pcContactName != null ?
                new ObjectParameter("pcContactName", pcContactName) :
                new ObjectParameter("pcContactName", typeof(string));
    
            var pcContactTitleParameter = pcContactTitle != null ?
                new ObjectParameter("pcContactTitle", pcContactTitle) :
                new ObjectParameter("pcContactTitle", typeof(string));
    
            var pcCityParameter = pcCity != null ?
                new ObjectParameter("pcCity", pcCity) :
                new ObjectParameter("pcCity", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcPostalCodeParameter = pcPostalCode != null ?
                new ObjectParameter("pcPostalCode", pcPostalCode) :
                new ObjectParameter("pcPostalCode", typeof(string));
    
            var pcCountryParameter = pcCountry != null ?
                new ObjectParameter("pcCountry", pcCountry) :
                new ObjectParameter("pcCountry", typeof(string));
    
            var pcPhoneParameter = pcPhone != null ?
                new ObjectParameter("pcPhone", pcPhone) :
                new ObjectParameter("pcPhone", typeof(string));
    
            var pcHomePageParameter = pcHomePage != null ?
                new ObjectParameter("pcHomePage", pcHomePage) :
                new ObjectParameter("pcHomePage", typeof(string));
    
            var pcAddressParameter = pcAddress != null ?
                new ObjectParameter("pcAddress", pcAddress) :
                new ObjectParameter("pcAddress", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_gmaradiaga_gestion_suppliers", pnTipoOperacionParameter, pnSupplierIDParameter, pcCompanyNameParameter, pcContactNameParameter, pcContactTitleParameter, pcCityParameter, pcRegionParameter, pcPostalCodeParameter, pcCountryParameter, pcPhoneParameter, pcHomePageParameter, pcAddressParameter, pcFaxParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_lgarcia_gestion_categorias(Nullable<int> pnTipoOperacion, Nullable<int> pnCategoryID, string pcCategoryName, string pcDescription, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcCategoryNameParameter = pcCategoryName != null ?
                new ObjectParameter("pcCategoryName", pcCategoryName) :
                new ObjectParameter("pcCategoryName", typeof(string));
    
            var pcDescriptionParameter = pcDescription != null ?
                new ObjectParameter("pcDescription", pcDescription) :
                new ObjectParameter("pcDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_lgarcia_gestion_categorias", pnTipoOperacionParameter, pnCategoryIDParameter, pcCategoryNameParameter, pcDescriptionParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual ObjectResult<sp_tsc_lgarcia_gestion_products_Result> sp_tsc_lgarcia_gestion_products(Nullable<int> pnTipoOperacion, Nullable<int> pnProductID, string pcProductName, Nullable<int> pnSupplierID, Nullable<int> pnCategoryID, string pcQuantityPerUnit, Nullable<decimal> pnUnitPrice, Nullable<short> pnUnitsInStock, Nullable<short> pnUnitsOnOrder, Nullable<short> pnReorderLevel, Nullable<bool> pbDiscontinued, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnProductIDParameter = pnProductID.HasValue ?
                new ObjectParameter("pnProductID", pnProductID) :
                new ObjectParameter("pnProductID", typeof(int));
    
            var pcProductNameParameter = pcProductName != null ?
                new ObjectParameter("pcProductName", pcProductName) :
                new ObjectParameter("pcProductName", typeof(string));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcQuantityPerUnitParameter = pcQuantityPerUnit != null ?
                new ObjectParameter("pcQuantityPerUnit", pcQuantityPerUnit) :
                new ObjectParameter("pcQuantityPerUnit", typeof(string));
    
            var pnUnitPriceParameter = pnUnitPrice.HasValue ?
                new ObjectParameter("pnUnitPrice", pnUnitPrice) :
                new ObjectParameter("pnUnitPrice", typeof(decimal));
    
            var pnUnitsInStockParameter = pnUnitsInStock.HasValue ?
                new ObjectParameter("pnUnitsInStock", pnUnitsInStock) :
                new ObjectParameter("pnUnitsInStock", typeof(short));
    
            var pnUnitsOnOrderParameter = pnUnitsOnOrder.HasValue ?
                new ObjectParameter("pnUnitsOnOrder", pnUnitsOnOrder) :
                new ObjectParameter("pnUnitsOnOrder", typeof(short));
    
            var pnReorderLevelParameter = pnReorderLevel.HasValue ?
                new ObjectParameter("pnReorderLevel", pnReorderLevel) :
                new ObjectParameter("pnReorderLevel", typeof(short));
    
            var pbDiscontinuedParameter = pbDiscontinued.HasValue ?
                new ObjectParameter("pbDiscontinued", pbDiscontinued) :
                new ObjectParameter("pbDiscontinued", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tsc_lgarcia_gestion_products_Result>("sp_tsc_lgarcia_gestion_products", pnTipoOperacionParameter, pnProductIDParameter, pcProductNameParameter, pnSupplierIDParameter, pnCategoryIDParameter, pcQuantityPerUnitParameter, pnUnitPriceParameter, pnUnitsInStockParameter, pnUnitsOnOrderParameter, pnReorderLevelParameter, pbDiscontinuedParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_lgarcia_gestion_suppliers(Nullable<int> pnTipoOperacion, Nullable<int> pnSupplierID, string pcCompanyName, string pcContactName, string pcContactTitle, string pcCity, string pcRegion, string pcPostalCode, string pcCountry, string pcPhone, string pcHomePage, string pcAddress, string pcFax, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pcCompanyNameParameter = pcCompanyName != null ?
                new ObjectParameter("pcCompanyName", pcCompanyName) :
                new ObjectParameter("pcCompanyName", typeof(string));
    
            var pcContactNameParameter = pcContactName != null ?
                new ObjectParameter("pcContactName", pcContactName) :
                new ObjectParameter("pcContactName", typeof(string));
    
            var pcContactTitleParameter = pcContactTitle != null ?
                new ObjectParameter("pcContactTitle", pcContactTitle) :
                new ObjectParameter("pcContactTitle", typeof(string));
    
            var pcCityParameter = pcCity != null ?
                new ObjectParameter("pcCity", pcCity) :
                new ObjectParameter("pcCity", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcPostalCodeParameter = pcPostalCode != null ?
                new ObjectParameter("pcPostalCode", pcPostalCode) :
                new ObjectParameter("pcPostalCode", typeof(string));
    
            var pcCountryParameter = pcCountry != null ?
                new ObjectParameter("pcCountry", pcCountry) :
                new ObjectParameter("pcCountry", typeof(string));
    
            var pcPhoneParameter = pcPhone != null ?
                new ObjectParameter("pcPhone", pcPhone) :
                new ObjectParameter("pcPhone", typeof(string));
    
            var pcHomePageParameter = pcHomePage != null ?
                new ObjectParameter("pcHomePage", pcHomePage) :
                new ObjectParameter("pcHomePage", typeof(string));
    
            var pcAddressParameter = pcAddress != null ?
                new ObjectParameter("pcAddress", pcAddress) :
                new ObjectParameter("pcAddress", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_lgarcia_gestion_suppliers", pnTipoOperacionParameter, pnSupplierIDParameter, pcCompanyNameParameter, pcContactNameParameter, pcContactTitleParameter, pcCityParameter, pcRegionParameter, pcPostalCodeParameter, pcCountryParameter, pcPhoneParameter, pcHomePageParameter, pcAddressParameter, pcFaxParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_lgarcia_obtener_categoria(Nullable<int> pnCategoryID, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_lgarcia_obtener_categoria", pnCategoryIDParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_lgarcia_obtener_producto(Nullable<int> pnProductID, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnProductIDParameter = pnProductID.HasValue ?
                new ObjectParameter("pnProductID", pnProductID) :
                new ObjectParameter("pnProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_lgarcia_obtener_producto", pnProductIDParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_lgarcia_obtener_suppliers(Nullable<int> pnSupplierID, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_lgarcia_obtener_suppliers", pnSupplierIDParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_rbarrientos_gestion_categories(Nullable<int> pnTipoOperacion, Nullable<int> pnCodigoRegistro, Nullable<int> pnCategoryID, string pcCategoryName, string pcDescription, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCodigoRegistroParameter = pnCodigoRegistro.HasValue ?
                new ObjectParameter("pnCodigoRegistro", pnCodigoRegistro) :
                new ObjectParameter("pnCodigoRegistro", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcCategoryNameParameter = pcCategoryName != null ?
                new ObjectParameter("pcCategoryName", pcCategoryName) :
                new ObjectParameter("pcCategoryName", typeof(string));
    
            var pcDescriptionParameter = pcDescription != null ?
                new ObjectParameter("pcDescription", pcDescription) :
                new ObjectParameter("pcDescription", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_rbarrientos_gestion_categories", pnTipoOperacionParameter, pnCodigoRegistroParameter, pnCategoryIDParameter, pcCategoryNameParameter, pcDescriptionParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_rbarrientos_gestion_products(Nullable<int> pnTipoOperacion, Nullable<int> pnCodigoRegistro, Nullable<int> pnProductID, string pcProductName, Nullable<int> pnSupplierID, Nullable<int> pnCategoryID, string pcQuantityPerUnit, Nullable<decimal> pnUnitPrice, Nullable<short> pnUnitsInStock, Nullable<short> pnUnitsOnOrder, Nullable<short> pnReorderLevel, Nullable<bool> pnDiscontinued, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnCodigoRegistroParameter = pnCodigoRegistro.HasValue ?
                new ObjectParameter("pnCodigoRegistro", pnCodigoRegistro) :
                new ObjectParameter("pnCodigoRegistro", typeof(int));
    
            var pnProductIDParameter = pnProductID.HasValue ?
                new ObjectParameter("pnProductID", pnProductID) :
                new ObjectParameter("pnProductID", typeof(int));
    
            var pcProductNameParameter = pcProductName != null ?
                new ObjectParameter("pcProductName", pcProductName) :
                new ObjectParameter("pcProductName", typeof(string));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcQuantityPerUnitParameter = pcQuantityPerUnit != null ?
                new ObjectParameter("pcQuantityPerUnit", pcQuantityPerUnit) :
                new ObjectParameter("pcQuantityPerUnit", typeof(string));
    
            var pnUnitPriceParameter = pnUnitPrice.HasValue ?
                new ObjectParameter("pnUnitPrice", pnUnitPrice) :
                new ObjectParameter("pnUnitPrice", typeof(decimal));
    
            var pnUnitsInStockParameter = pnUnitsInStock.HasValue ?
                new ObjectParameter("pnUnitsInStock", pnUnitsInStock) :
                new ObjectParameter("pnUnitsInStock", typeof(short));
    
            var pnUnitsOnOrderParameter = pnUnitsOnOrder.HasValue ?
                new ObjectParameter("pnUnitsOnOrder", pnUnitsOnOrder) :
                new ObjectParameter("pnUnitsOnOrder", typeof(short));
    
            var pnReorderLevelParameter = pnReorderLevel.HasValue ?
                new ObjectParameter("pnReorderLevel", pnReorderLevel) :
                new ObjectParameter("pnReorderLevel", typeof(short));
    
            var pnDiscontinuedParameter = pnDiscontinued.HasValue ?
                new ObjectParameter("pnDiscontinued", pnDiscontinued) :
                new ObjectParameter("pnDiscontinued", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_rbarrientos_gestion_products", pnTipoOperacionParameter, pnCodigoRegistroParameter, pnProductIDParameter, pcProductNameParameter, pnSupplierIDParameter, pnCategoryIDParameter, pcQuantityPerUnitParameter, pnUnitPriceParameter, pnUnitsInStockParameter, pnUnitsOnOrderParameter, pnReorderLevelParameter, pnDiscontinuedParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_tsc_rbarrientos_gestion_suppliers(Nullable<int> pnTipoOperacion, Nullable<int> pnSupplierID, string pcCompanyName, string pcContactName, string pcContactTitle, string pcCity, string pcRegion, string pcPostalCode, string pcCountry, string pcPhone, string pcHomePage, string pcAddress, string pcFax, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnTipoOperacionParameter = pnTipoOperacion.HasValue ?
                new ObjectParameter("pnTipoOperacion", pnTipoOperacion) :
                new ObjectParameter("pnTipoOperacion", typeof(int));
    
            var pnSupplierIDParameter = pnSupplierID.HasValue ?
                new ObjectParameter("pnSupplierID", pnSupplierID) :
                new ObjectParameter("pnSupplierID", typeof(int));
    
            var pcCompanyNameParameter = pcCompanyName != null ?
                new ObjectParameter("pcCompanyName", pcCompanyName) :
                new ObjectParameter("pcCompanyName", typeof(string));
    
            var pcContactNameParameter = pcContactName != null ?
                new ObjectParameter("pcContactName", pcContactName) :
                new ObjectParameter("pcContactName", typeof(string));
    
            var pcContactTitleParameter = pcContactTitle != null ?
                new ObjectParameter("pcContactTitle", pcContactTitle) :
                new ObjectParameter("pcContactTitle", typeof(string));
    
            var pcCityParameter = pcCity != null ?
                new ObjectParameter("pcCity", pcCity) :
                new ObjectParameter("pcCity", typeof(string));
    
            var pcRegionParameter = pcRegion != null ?
                new ObjectParameter("pcRegion", pcRegion) :
                new ObjectParameter("pcRegion", typeof(string));
    
            var pcPostalCodeParameter = pcPostalCode != null ?
                new ObjectParameter("pcPostalCode", pcPostalCode) :
                new ObjectParameter("pcPostalCode", typeof(string));
    
            var pcCountryParameter = pcCountry != null ?
                new ObjectParameter("pcCountry", pcCountry) :
                new ObjectParameter("pcCountry", typeof(string));
    
            var pcPhoneParameter = pcPhone != null ?
                new ObjectParameter("pcPhone", pcPhone) :
                new ObjectParameter("pcPhone", typeof(string));
    
            var pcHomePageParameter = pcHomePage != null ?
                new ObjectParameter("pcHomePage", pcHomePage) :
                new ObjectParameter("pcHomePage", typeof(string));
    
            var pcAddressParameter = pcAddress != null ?
                new ObjectParameter("pcAddress", pcAddress) :
                new ObjectParameter("pcAddress", typeof(string));
    
            var pcFaxParameter = pcFax != null ?
                new ObjectParameter("pcFax", pcFax) :
                new ObjectParameter("pcFax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tsc_rbarrientos_gestion_suppliers", pnTipoOperacionParameter, pnSupplierIDParameter, pcCompanyNameParameter, pcContactNameParameter, pcContactTitleParameter, pcCityParameter, pcRegionParameter, pcPostalCodeParameter, pcCountryParameter, pcPhoneParameter, pcHomePageParameter, pcAddressParameter, pcFaxParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    
        public virtual int sp_usr_jhmedina_gestion_categorias(Nullable<int> pnOperationType, Nullable<int> pnCategoryID, string pcCategoryName, string pcDescripcion, byte[] pcPicture, ObjectParameter pnTypeResult, ObjectParameter pnCodeResult, ObjectParameter pcResult, ObjectParameter pcMessage)
        {
            var pnOperationTypeParameter = pnOperationType.HasValue ?
                new ObjectParameter("pnOperationType", pnOperationType) :
                new ObjectParameter("pnOperationType", typeof(int));
    
            var pnCategoryIDParameter = pnCategoryID.HasValue ?
                new ObjectParameter("pnCategoryID", pnCategoryID) :
                new ObjectParameter("pnCategoryID", typeof(int));
    
            var pcCategoryNameParameter = pcCategoryName != null ?
                new ObjectParameter("pcCategoryName", pcCategoryName) :
                new ObjectParameter("pcCategoryName", typeof(string));
    
            var pcDescripcionParameter = pcDescripcion != null ?
                new ObjectParameter("pcDescripcion", pcDescripcion) :
                new ObjectParameter("pcDescripcion", typeof(string));
    
            var pcPictureParameter = pcPicture != null ?
                new ObjectParameter("pcPicture", pcPicture) :
                new ObjectParameter("pcPicture", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_usr_jhmedina_gestion_categorias", pnOperationTypeParameter, pnCategoryIDParameter, pcCategoryNameParameter, pcDescripcionParameter, pcPictureParameter, pnTypeResult, pnCodeResult, pcResult, pcMessage);
        }
    }
}
